name: Python CI/CD
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          environment-file: environment.yml
          auto-update-conda: true
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Run tests
        run: |
          source activate myenv
          cd python-scripts
          pytest
