name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.0
  - pandas=2.1.1
  - psycopg2=2.9.7
  - sqlalchemy=2.1.2
  - requests=2.31.0
  - pytest=7.4.2
  - matplotlib=3.8.1
  - seaborn=0.13.0
  - jupyterlab=4.0.5
